### ISSUE TITLE
Incorrect version dependency for version 1.20

### ISSUE THREAD

**Issue by Duckoboye** [Taskeren/mineQuery-1.17#13]
The fabric.mod.json file incorrectly depends on minecraft version 1.19.x which prevents you from actually using your mod. It should be changed from "1.19.x" to "1.20.x"

**Comment by Taskeren** [comment]
Fixed.
Thanks for reporting!

**Comment by Duckoboye** [comment]
It seems like the current build on modrinth is still not playable. I suspect this is because of the line "fabricloader": ">=0.83.0", which is incorrectly set to the API version and not the  fabric loader version. This should be "fabricloader": ">=0.14.6" as it was previously.

**Comment by Taskeren** [comment]
Now should fix.
I'm so sorry that I didn't check if it works.
Thanks again for your report!

**Comment by Duckoboye** [comment]
No worries. Thank you for your excellent mod!
